import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import path from 'node:path'

const root = path.resolve(__dirname, '../..')

function readSource(relativePath: string): string {
  return readFileSync(path.join(root, relativePath), 'utf8')
}

describe('通知送信の回帰防止', () => {
  it('/api/run-now は送信成功後だけ notified_items に保存する', () => {
    const source = readSource('app/api/run-now/route.ts')
    const deliveryCheck = source.indexOf('if (delivered) {')
    const markNotified = source.indexOf('await markNotified(userId, item.auctionId)')
    const retryWarning = source.indexOf('notified_items に記録せず次回再試行')

    expect(deliveryCheck).toBeGreaterThan(-1)
    expect(markNotified).toBeGreaterThan(deliveryCheck)
    expect(retryWarning).toBeGreaterThan(-1)
  })

  it('GitHub Actions run-check もPush成功後だけ notified_items に保存する', () => {
    const source = readSource('scripts/run-check.ts')
    const deliveryCheck = source.indexOf('if (!delivered) {')
    const addHistory = source.indexOf('await addHistory(toHistoryRecord(cond, item))')
    const markNotified = source.indexOf('await markNotified(userId, item.auctionId)')
    const retryWarning = source.indexOf('通知済みにせず次回再試行')
    const recordRetryWarning = source.indexOf('未記録分は次回再試行')

    expect(deliveryCheck).toBeGreaterThan(-1)
    expect(markNotified).toBeGreaterThan(deliveryCheck)
    expect(addHistory).toBeGreaterThan(deliveryCheck)
    expect(markNotified).toBeGreaterThan(addHistory)
    expect(retryWarning).toBeGreaterThan(-1)
    expect(recordRetryWarning).toBeGreaterThan(-1)
  })

  it('GitHub Actions run-check は自己修復を通知判定前に実行する', () => {
    const source = readSource('scripts/run-check.ts')
    const reset = source.indexOf('await resetStalledNotified()')
    const cache = source.indexOf('await getAllNotifiedIds(activeUserIds)')
    const summary = source.indexOf('await sendWebPushSummary')

    expect(reset).toBeGreaterThan(-1)
    expect(cache).toBeGreaterThan(reset)
    expect(summary).toBeGreaterThan(cache)
  })

  it('ストレージ層は通知履歴と通知済み保存のSupabaseエラーを握りつぶさない', () => {
    const source = readSource('lib/storage.ts')

    expect(source).toContain('function throwOnError')
    expect(source).toContain("throwOnError(insertErr, 'notification_history保存エラー')")
    expect(source).toContain("throwOnError(error, 'notified_items保存エラー')")
  })

  it('条件保存後に全条件run-nowを重ねて起動しない', () => {
    const source = readSource('app/page.tsx')

    expect(source).not.toContain("fetch('/api/run-now'")
    expect(source).not.toContain('runNow()')
  })

  it('定期チェック完了通知を環境変数で有効化できる', () => {
    const runCheck = readSource('scripts/run-check.ts')
    const runNow = readSource('app/api/run-now/route.ts')
    const workflow = readSource('.github/workflows/cron.yml')
    const webpush = readSource('lib/webpush.ts')

    expect(runCheck).toContain('SEND_NO_ITEMS_PUSH')
    expect(runCheck).toContain('FORCE_CHECK_COMPLETE_PUSH')
    expect(runCheck).toContain('await sendWebPushCheckComplete(userId')
    expect(runCheck).toContain('failedFetchByUser')
    expect(runNow).toContain('SEND_NO_ITEMS_PUSH')
    expect(runNow).toContain('await sendWebPushCheckComplete(userId')
    expect(runNow).toContain('fetchFailedCount')
    expect(workflow).toContain("SEND_NO_ITEMS_PUSH: 'true'")
    expect(workflow).toContain('force_check_complete')
    expect(workflow).toContain('stamp_last_checked_only')
    expect(workflow).toContain('scripts/stamp-last-checked.ts')
    expect(workflow).toContain("cron: '7 22,23 * * *'")
    expect(workflow).toContain("cron: '7 0-15 * * *'")
    expect(runCheck).toContain('canSendCheckCompleteThisHour')
    expect(runCheck).toContain('チェック完了Pushは50分以内に送信済み')
    expect(runCheck).toContain("process.env.GH_FETCH_PAGES ?? '40'")
    expect(runCheck).toContain('CHECK_SHARD_TOTAL')
    expect(runCheck).toContain('CHECK_FETCH_CONCURRENCY')
    expect(runCheck).toContain('stringShard')
    expect(runCheck).toContain('検索グループ単位')
    expect(runCheck).toContain('reserveCheckCompleteThisHour')
    expect(runCheck).toContain('チェック完了Pushは他シャードで処理済み')
    expect(runCheck).toContain('上限到達')
    expect(runCheck).toContain('isJstQuietHour')
    expect(runCheck).toContain('ALLOW_NIGHT_NOTIFICATIONS')
    expect(runCheck).toContain('JST 25:00-06:59 は通知停止時間')
    expect(webpush).toContain('新着はありませんでした')
    expect(webpush).toContain('取得できませんでした')
  })

  it('端末側のPush受信ACKと強制再登録が実装されている', () => {
    const sw = readSource('public/sw.js')
    const receipt = readSource('app/api/push/receipt/route.ts')
    const pushClient = readSource('lib/push-client.ts')
    const settings = readSource('app/settings/page.tsx')
    const page = readSource('app/page.tsx')

    expect(sw).toContain("CACHE_VERSION = 'v14'")
    expect(sw).toContain('/api/push/receipt')
    expect(receipt).toContain('[push/receipt] service-worker-received')
    expect(pushClient).toContain('options.forceRefresh')
    expect(settings).toContain('enablePush(true)')
    expect(settings).toContain('通知を再登録する')
    expect(page).toContain('PUSH_SETUP_REMINDER_KEY')
    expect(page).toContain('通知設定が必要です')
    expect(page).toContain('設定しないと新着通知を受け取れません')
    expect(page).toContain('showPushSetupReminder')
  })

  it('48時間以内終了の商品を通知対象にし、重複防止ログは60時間保持する', () => {
    const scraper = readSource('lib/scraper.ts')
    const storage = readSource('lib/storage.ts')
    const runCheck = readSource('scripts/run-check.ts')
    const matcher = readSource('lib/condition-match.ts')

    expect(scraper).toContain('ENDING_SOON_WINDOW_HOURS = 48')
    expect(scraper).toContain('開催中 + 48時間以内フィルター')
    expect(scraper).toContain('shouldStopEndTimePage')
    expect(scraper).toContain('item.endtimeMs - now <= ENDING_SOON_WINDOW_MS')
    expect(scraper).not.toContain("aucend:      '1'")
    expect(storage).toContain('60時間以上古い重複防止レコードを削除')
    expect(storage).toContain('60 * 60 * 60 * 1000')
    expect(runCheck).toContain('/ 48h ${items.length}件')
    expect(runCheck).toContain('selectConditionCandidates')
    expect(matcher).toContain('厳密一致が0件の時だけ入札数条件を候補条件へ')
    expect(scraper).toContain('hasYahooSideNarrowing')
    expect(scraper).toContain('ストア/中古/出品形式と入札数順')
  })

  it('通知履歴はDB削除せず、履歴消失を防ぐ', () => {
    const historyRoute = readSource('app/api/history/route.ts')
    const historyRestoreRoute = readSource('app/api/history/restore/route.ts')
    const historyPage = readSource('app/history/page.tsx')
    const storage = readSource('lib/storage.ts')
    const runCheck = readSource('scripts/run-check.ts')
    const cronRoute = readSource('app/api/cron/check/route.ts')
    const cronShardRoute = readSource('app/api/cron/check/[shard]/route.ts')
    const restoreScript = readSource('scripts/restore-history.ts')

    expect(historyRoute).not.toContain('cleanupEndedHistoryForUser(userId)')
    expect(historyRestoreRoute).toContain('await addHistory(record)')
    expect(historyPage).toContain('/api/history/restore')
    expect(historyPage).toContain('readCachedHistory')
    expect(historyPage).toContain('data.length === 0 && cached.length > 0')
    expect(storage).toContain('cleanupEndedHistoryForUser')
    expect(storage).toContain('終了済み履歴のDB削除は一時停止')
    expect(storage).toContain('notification_history のDB削除は一時停止')
    expect(storage).toContain('ENDED_AUCTION_HISTORY_VISIBLE_MS')
    expect(storage).toContain('終了後24時間以内だけ表示')
    expect(storage).toContain('isVisibleHistoryRow')
    expect(runCheck).toContain('終了済みオークション削除は一時停止中')
    expect(cronRoute).toContain('終了済みオークション削除は一時停止中')
    expect(cronShardRoute).toContain('終了済みオークション削除は一時停止中')
    expect(cronRoute).not.toContain(".lte('end_at'")
    expect(cronShardRoute).not.toContain(".lte('end_at'")
    expect(restoreScript).toContain('restoreCurrentMatches')
    expect(restoreScript).toContain('restoreFromNotifiedItems')
    expect(restoreScript).toContain('通知履歴復旧スクリプト')
  })

  it('巡回成功時は件数変化がなくても最終チェック時刻を更新する', () => {
    const runCheck = readSource('scripts/run-check.ts')
    const runNow = readSource('app/api/run-now/route.ts')

    expect(runCheck).toContain('巡回成功の証跡として必ず更新')
    expect(runCheck).toContain('await updateCondition(cond.id, {')
    expect(runCheck).not.toContain('変化があった時のみ更新')
    expect(runNow).toContain('await updateCondition(cond.id, {')
    expect(runNow).not.toContain('items.length !== (cond.lastFoundCount ?? -1)')
  })

  it('GitHub scheduleは深夜停止し、バックアップworkflowは手動専用にする', () => {
    const backupWorkflow = readSource('.github/workflows/cron-backup.yml')
    const workflow = readSource('.github/workflows/cron.yml')
    const conditionCard = readSource('components/ConditionCard.tsx')

    expect(backupWorkflow).not.toContain('schedule:')
    expect(backupWorkflow).toContain('workflow_dispatch')
    expect(backupWorkflow).toContain('yahoo-auction-watch-check')
    expect(backupWorkflow).toContain("SEND_NO_ITEMS_PUSH: 'true'")
    expect(backupWorkflow).toContain("GH_FETCH_PAGES: '40'")
    expect(backupWorkflow).toContain("CHECK_SHARD_TOTAL: '6'")
    expect(backupWorkflow).toContain('CHECK_SHARD_INDEX: ${{ matrix.shard }}')
    expect(backupWorkflow).toContain("CHECK_FETCH_CONCURRENCY: '3'")
    expect(backupWorkflow).toContain('timeout-minutes: 30')
    expect(backupWorkflow).toContain('matrix:')
    expect(workflow).toContain("cron: '7 22,23 * * *'")
    expect(workflow).toContain("cron: '7 0-15 * * *'")
    expect(workflow).toContain("GH_FETCH_PAGES: '40'")
    expect(workflow).toContain("CHECK_SHARD_TOTAL: '6'")
    expect(workflow).toContain('CHECK_SHARD_INDEX: ${{ matrix.shard }}')
    expect(workflow).toContain("CHECK_FETCH_CONCURRENCY: '3'")
    expect(workflow).toContain("SUPABASE_FETCH_TIMEOUT_MS: '90000'")
    expect(workflow).toContain('timeout-minutes: 30')
    expect(workflow).toContain('matrix:')
    expect(conditionCard).toContain("hourCycle: 'h23'")
    expect(conditionCard).toContain("timeZone: 'Asia/Tokyo'")
  })

  it('アプリ起動時に最終チェック表示を更新し、DB更新できない時も端末表示で補完する', () => {
    const page = readSource('app/page.tsx')
    const conditionCard = readSource('components/ConditionCard.tsx')
    const stampRoute = readSource('app/api/conditions/stamp/route.ts')
    const storage = readSource('lib/storage.ts')

    expect(page).toContain('CHECK_DISPLAY_STAMP_KEY')
    expect(page).toContain('/api/conditions/stamp')
    expect(page).toContain('displayCheckedAt={displayCheckedAt}')
    expect(conditionCard).toContain('function latestIso')
    expect(conditionCard).toContain('condition.enabled ? displayCheckedAt : null')
    expect(stampRoute).toContain('stampEnabledConditionsForUser')
    expect(storage).toContain('stampEnabledConditionsForUser')
    expect(storage).toContain('last_checked_at: checkedAt')
  })

  it('商品がなくても条件チェック履歴を残す', () => {
    const storage = readSource('lib/storage.ts')
    const runCheck = readSource('scripts/run-check.ts')
    const runNow = readSource('app/api/run-now/route.ts')
    const historyPage = readSource('app/history/page.tsx')
    const webpush = readSource('lib/webpush.ts')

    expect(storage).toContain('addConditionCheckHistory')
    expect(storage).toContain('条件チェック: 新着はありませんでした')
    expect(storage).toContain('__check_')
    expect(runCheck).toContain('addConditionCheckHistory(cond')
    expect(runNow).toContain('addConditionCheckHistory(cond')
    expect(historyPage).toContain('条件チェック')
    expect(webpush).toContain('新着はありませんでした')
    expect(storage).toContain(".not('auction_id', 'like', '__check_%')")
  })
})
